<?php
require_once __DIR__ . '/_admin_helpers.php';
try{
 admin_require(); $db=admin_db();
 $users=['total'=>admin_count($db,'SELECT COUNT(*) FROM users'),'active'=>admin_count($db,"SELECT COUNT(*) FROM users WHERE status='active'"),'suspended'=>admin_count($db,"SELECT COUNT(*) FROM users WHERE status='suspended'")];
 $memories=['total'=>admin_count($db,"SELECT COUNT(*) FROM memories WHERE status='active'"),'storage_bytes'=>admin_sum($db,"SELECT COALESCE(SUM(file_size),0) FROM memories WHERE status='active'")];
 $posts=['posts'=>admin_count($db,"SELECT COUNT(*) FROM posts WHERE status='active'"),'post_comments'=>admin_count($db,"SELECT COUNT(*) FROM post_comments WHERE deleted_at IS NULL"),'memory_comments'=>admin_count($db,"SELECT COUNT(*) FROM memory_comments WHERE deleted_at IS NULL")];
 $social=['family_members'=>admin_count($db,"SELECT COUNT(*) FROM family_members WHERE status='active'"),'friendships'=>admin_count($db,"SELECT COUNT(*) FROM friendships WHERE status='accepted'"),'friend_requests_pending'=>admin_count($db,"SELECT COUNT(*) FROM friend_requests WHERE status='pending'")];
 $journeys=['total'=>admin_count($db,"SELECT COUNT(*) FROM journeys WHERE deleted_at IS NULL"),'published'=>admin_count($db,"SELECT COUNT(*) FROM journeys WHERE status='published' AND deleted_at IS NULL"),'pending_items'=>admin_count($db,"SELECT COUNT(*) FROM journey_items WHERE status='pending' AND deleted_at IS NULL")];
 $automation=['scheduled_events'=>admin_count($db,"SELECT COUNT(*) FROM scheduled_events WHERE status='scheduled'"),'automation_rules'=>admin_count($db,"SELECT COUNT(*) FROM automation_rules WHERE deleted_at IS NULL"),'failed_automations'=>admin_count($db,"SELECT COUNT(*) FROM automation_rules WHERE status='failed' AND deleted_at IS NULL"),'scheduled_wall_posts'=>admin_count($db,"SELECT COUNT(*) FROM scheduled_wall_posts WHERE status='scheduled' AND deleted_at IS NULL")];
 $vault=['documents'=>admin_count($db,"SELECT COUNT(*) FROM vault_documents WHERE deleted_at IS NULL"),'folders'=>admin_count($db,"SELECT COUNT(*) FROM vault_folders WHERE deleted_at IS NULL"),'storage_bytes'=>admin_sum($db,"SELECT COALESCE(SUM(file_size),0) FROM vault_documents WHERE deleted_at IS NULL"),'permissions'=>admin_count($db,"SELECT COUNT(*) FROM vault_permissions WHERE status='active'")];
 $ai=['sources'=>admin_count($db,"SELECT COUNT(*) FROM ai_sources WHERE deleted_at IS NULL"),'indexed_sources'=>admin_count($db,"SELECT COUNT(*) FROM ai_sources WHERE ingestion_status='indexed' AND deleted_at IS NULL"),'failed_sources'=>admin_count($db,"SELECT COUNT(*) FROM ai_sources WHERE ingestion_status='failed' AND deleted_at IS NULL"),'chunks'=>admin_count($db,'SELECT COUNT(*) FROM ai_chunks'),'conversations'=>admin_count($db,"SELECT COUNT(*) FROM ai_conversations WHERE status='active'"),'autobiographies'=>admin_count($db,"SELECT COUNT(*) FROM ai_autobiographies WHERE deleted_at IS NULL"),'personalized_messages'=>admin_count($db,"SELECT COUNT(*) FROM ai_personalized_messages WHERE deleted_at IS NULL"),'tokens'=>admin_sum($db,"SELECT COALESCE(SUM(total_tokens),0) FROM ai_personalized_messages WHERE deleted_at IS NULL") + admin_sum($db,"SELECT COALESCE(SUM(total_tokens),0) FROM ai_autobiographies WHERE deleted_at IS NULL") + admin_sum($db,"SELECT COALESCE(SUM(total_tokens),0) FROM ai_messages")];
 $gifts=['orders'=>admin_count($db,"SELECT COUNT(*) FROM gift_orders WHERE deleted_at IS NULL"),'failed'=>admin_count($db,"SELECT COUNT(*) FROM gift_orders WHERE status='failed' AND deleted_at IS NULL"),'integration'=>getenv('PHOOLWALA_API_KEY')&&getenv('PHOOLWALA_API_URL')?'Configured':'Not Configured / Pending API credentials'];
 $failed=['ai_jobs'=>admin_rows($db,"SELECT id,source_id,status,error_code,attempts,available_at FROM ai_ingestion_jobs WHERE status='failed' ORDER BY updated_at DESC LIMIT 20"),'automations'=>admin_rows($db,"SELECT id,title,status,last_error,retry_count,next_run_at FROM automation_rules WHERE status='failed' AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 20")];
 $recent=['activity'=>admin_rows($db,"SELECT a.id,u.username,a.action,a.details,a.created_at FROM activity_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 20"),'automation_runs'=>admin_rows($db,"SELECT ar.id,ar.rule_id,ar.status,ar.error_message,ar.started_at FROM automation_runs ar ORDER BY ar.started_at DESC LIMIT 20")];
 ApiResponse::success(compact('users','memories','posts','social','journeys','automation','vault','ai','gifts','failed','recent'),'Admin overview loaded.');
}catch(Throwable $e){Logger::error('Admin overview failed',['error'=>$e->getMessage()]);ApiResponse::serverError('Unable to load admin overview.');}
?>
