const GIFTS_API='http://localhost/IAmStillHere/backend/gifts';
let giftCatalog=[];
function giftEl(id){return document.getElementById(id);}
function giftStatus(msg,type='muted'){const el=giftEl('gift-status');if(el){el.className=`small text-${type} mb-2`;el.textContent=msg;}}
function giftLocalIso(v){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString();}
async function giftJson(r){const t=await r.text();try{return JSON.parse(t);}catch(e){throw new Error('Server returned invalid JSON.');}}
async function giftLoadCatalog(){giftStatus('Loading catalog...');try{const d=await giftJson(await fetch(`${GIFTS_API}/catalog.php`,{cache:'no-store'}));if(!d.success)throw new Error(d.message||'Catalog failed.');giftCatalog=Array.isArray(d.data.catalog?.items)?d.data.catalog.items:(Array.isArray(d.data.catalog)?d.data.catalog:[]);const sel=giftEl('gift-catalog');sel.innerHTML='<option value="">Select gift</option>';giftCatalog.forEach(g=>{const id=g.id||g.gift_id||g.sku;const name=g.name||g.title||'Gift';if(!id)return;const o=document.createElement('option');o.value=id;o.textContent=name+(g.price?` - ${g.price} ${g.currency||''}`:'');o.dataset.name=name;o.dataset.price=g.price||'';o.dataset.currency=g.currency||'';sel.appendChild(o);});giftStatus(giftCatalog.length?'Catalog loaded.':'Catalog empty.','success');}catch(e){giftStatus(e.message,'danger');}}
function giftPayload(){const sel=giftEl('gift-catalog');const opt=sel.options[sel.selectedIndex];return {csrf_token:csrfToken,gift_external_id:sel.value,gift_name:opt?.dataset.name||opt?.textContent||'Selected gift',gift_price:opt?.dataset.price||'',gift_currency:opt?.dataset.currency||'',recipient_name:giftEl('gift-recipient-name').value.trim(),recipient_email:giftEl('gift-recipient-email').value.trim(),recipient_address:giftEl('gift-address').value.trim(),occasion:giftEl('gift-occasion').value,delivery_at:giftLocalIso(giftEl('gift-delivery-at').value),message_text:giftEl('gift-message').value.trim(),idempotency_key:''};}
async function giftCreate(){giftStatus('Creating gift order...','primary');try{const d=await giftJson(await fetch(`${GIFTS_API}/create_order.php`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify(giftPayload())}));if(!d.success)throw new Error(d.message||'Order failed.');giftStatus('Gift order created.','success');giftLoadOrders();}catch(e){giftStatus(e.message,'danger');}}
async function giftCancel(id){if(!confirm('Cancel gift order?'))return;try{const d=await giftJson(await fetch(`${GIFTS_API}/cancel.php`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({csrf_token:csrfToken,order_id:id})}));giftStatus(d.message||'Done',d.success?'success':'danger');giftLoadOrders();}catch(e){giftStatus(e.message,'danger');}}
async function giftLoadOrders(){try{const d=await giftJson(await fetch(`${GIFTS_API}/list.php`,{cache:'no-store'}));if(!d.success)throw new Error(d.message||'Load failed.');const list=giftEl('gift-orders-list');const rows=d.data.orders||[];list.innerHTML=rows.length?rows.map(o=>`<div class="col-md-6"><div class="border rounded p-2 h-100"><div class="d-flex justify-content-between"><strong>${escapeHtml(o.gift_name||'Gift')}</strong><span class="badge bg-secondary">${escapeHtml(o.status)}</span></div><div class="small text-muted">${escapeHtml(o.occasion||'custom')}  -  ${escapeHtml(o.delivery_at||'')}</div><div class="small">${escapeHtml(o.recipient_name||'Recipient')}</div>${['scheduled','pending_payment','placed'].includes(o.status)?`<button class="btn btn-outline-danger btn-sm mt-2" onclick="giftCancel(${o.id})">Cancel</button>`:''}</div></div>`).join(''):'<div class="text-muted small">No gift orders yet.</div>';}catch(e){giftStatus(e.message,'danger');}}
document.addEventListener('DOMContentLoaded',()=>{if(!giftEl('gifts-card'))return;giftEl('gift-load-catalog')?.addEventListener('click',giftLoadCatalog);giftEl('gift-create')?.addEventListener('click',giftCreate);giftEl('gift-refresh')?.addEventListener('click',giftLoadOrders);giftLoadOrders();});
