const PM_API='/backend/ai/personalized_messages';
let pmBusy=false;
function pmVal(id){return document.getElementById(id)?.value||'';}
function pmSet(id,v){const e=document.getElementById(id);if(e)e.value=v||'';}
function pmStatus(t,cls='muted'){const e=document.getElementById('pm-status');if(e){e.className=`small text-${cls} mb-2`;e.textContent=t||'';}}
function pmEsc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML;}
async function pmJson(r){const t=await r.text();try{return JSON.parse(t);}catch(e){throw new Error(t.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().substring(0,180)||'Invalid server response.');}}
function pmLocalToIso(value){if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toISOString();}
function pmUtcToLocalInput(value){if(!value)return '';const d=new Date(String(value).replace(' ','T')+'Z');if(Number.isNaN(d.getTime()))return '';const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function pmPayload(){return {csrf_token:csrfToken,message_id:Number(pmVal('pm-id')||0),recipient_user_id:Number(pmVal('pm-recipient-user')||0),recipient_email:pmVal('pm-recipient-email'),recipient_name:pmVal('pm-recipient-name'),relationship:pmVal('pm-relationship'),event_type:pmVal('pm-event-type'),trigger_at:pmLocalToIso(pmVal('pm-trigger-at')),delivery_method:pmVal('pm-delivery'),tone:pmVal('pm-tone'),instructions:pmVal('pm-instructions'),edited_message:pmVal('pm-message')};}
function pmFill(m){pmSet('pm-id',m.id);pmSet('pm-recipient-user',m.recipient_user_id);pmSet('pm-recipient-email',m.recipient_email);pmSet('pm-recipient-name',m.recipient_name||m.recipient_user_name);pmSet('pm-relationship',m.relationship);pmSet('pm-event-type',m.event_type);pmSet('pm-trigger-at',pmUtcToLocalInput(m.trigger_at));pmSet('pm-delivery',m.delivery_method);pmSet('pm-tone',m.tone);pmSet('pm-instructions',m.instructions);pmSet('pm-message',m.edited_message||m.generated_message);}
function pmButtons(disabled){['pm-generate','pm-save','pm-schedule','pm-cancel'].forEach(id=>{const e=document.getElementById(id);if(e)e.disabled=disabled;});const g=document.getElementById('pm-generate');if(g)g.innerHTML=disabled?'<span class="spinner-border spinner-border-sm me-1"></span>Working...':'Generate Draft';}
async function pmPost(endpoint,payload){const r=await fetch(`${PM_API}/${endpoint}.php`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify(payload)});const d=await pmJson(r);if(!d.success)throw new Error(d.message||'Request failed.');return d.data;}
async function pmGenerate(){if(pmBusy)return;pmBusy=true;pmButtons(true);pmStatus('Generating draft from approved AI knowledge...','primary');try{const d=await pmPost('generate',pmPayload());pmFill(d.message);pmStatus('Draft generated. Edit it before scheduling.','success');pmLoad();}catch(e){pmStatus(e.message,'danger');}finally{pmBusy=false;pmButtons(false);}}
async function pmSave(){if(pmBusy)return;pmBusy=true;pmButtons(true);pmStatus('Saving draft...','primary');try{const d=await pmPost('save',pmPayload());pmFill(d.message);pmStatus('Draft saved.','success');pmLoad();}catch(e){pmStatus(e.message,'danger');}finally{pmBusy=false;pmButtons(false);}}
async function pmSchedule(){if(pmBusy)return;const id=Number(pmVal('pm-id')||0);if(!id){pmStatus('Generate or save a draft first.','danger');return;}pmBusy=true;pmButtons(true);pmStatus('Scheduling through Event Automation...','primary');try{const saved=await pmPost('save',pmPayload());pmFill(saved.message);const d=await pmPost('schedule',{csrf_token:csrfToken,message_id:id});pmFill(d.message);pmStatus('Message scheduled.','success');pmLoad();}catch(e){pmStatus(e.message,'danger');}finally{pmBusy=false;pmButtons(false);}}
async function pmCancel(){const id=Number(pmVal('pm-id')||0);if(!id)return;if(!confirm('Cancel this personalized message?'))return;try{const d=await pmPost('cancel',{csrf_token:csrfToken,message_id:id});pmFill(d.message);pmStatus('Message cancelled.','success');pmLoad();}catch(e){pmStatus(e.message,'danger');}}
async function pmLoadRecipients(){const sel=document.getElementById('pm-recipient-user');if(!sel)return;try{const r=await fetch(`${PM_API}/recipients.php`,{cache:'no-store'});const d=await pmJson(r);if(!d.success)return;(d.data.recipients||[]).forEach(u=>{const o=document.createElement('option');o.value=u.id;o.textContent=u.full_name;sel.appendChild(o);});}catch(e){}}
async function pmLoad(){const box=document.getElementById('personalized-messages-list');if(!box)return;try{const r=await fetch(`${PM_API}/list.php`,{cache:'no-store'});const d=await pmJson(r);if(!d.success)throw new Error(d.message);const rows=d.data.messages||[];box.innerHTML=rows.length?rows.map(m=>`<div class="col-12"><div class="border rounded p-2 bg-white"><div class="d-flex justify-content-between gap-2"><strong>${pmEsc(m.event_type)}</strong><span class="badge bg-secondary">${pmEsc(m.status)}</span></div><div class="small text-muted">${pmEsc(m.recipient_user_name||m.recipient_name||m.recipient_email||'Wall post')} • ${pmEsc(m.trigger_at||'not scheduled')}</div><div class="small text-truncate">${pmEsc(m.edited_message||m.generated_message||'')}</div><button class="btn btn-link btn-sm p-0" onclick='pmFill(${JSON.stringify(m).replace(/'/g,"&#39;")})'>Edit</button></div></div>`).join(''):'<div class="text-muted small">No personalized messages yet.</div>';}catch(e){box.innerHTML=`<div class="text-danger small">${pmEsc(e.message)}</div>`;}}
function initPM(){if(!document.getElementById('personalized-message-form')||document.body.dataset.pmReady==='1')return;document.body.dataset.pmReady='1';document.getElementById('pm-generate')?.addEventListener('click',pmGenerate);document.getElementById('pm-save')?.addEventListener('click',pmSave);document.getElementById('pm-schedule')?.addEventListener('click',pmSchedule);document.getElementById('pm-cancel')?.addEventListener('click',pmCancel);pmLoadRecipients();pmLoad();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initPM);else initPM();
