const PRIVACY_API = 'http://localhost/IAmStillHere/backend/privacy/rules';

function privacyComponent(prefix, ownerId) {
    const wrap = document.createElement('div');
    wrap.className = 'privacy-component';
    wrap.innerHTML = `<label class="form-label">Privacy</label><select class="form-select privacy-type"><option value="public">Public</option><option value="family">Family</option><option value="friends">Friends</option><option value="specific_people">Specific People</option><option value="private">Private</option><option value="release_date">Release on Date</option><option value="release_event">Release on Event</option></select><div class="privacy-specific mt-2 d-none"><label class="form-label">People</label><select multiple class="form-select privacy-users"></select></div><div class="privacy-date mt-2 d-none"><label class="form-label">Release time (UTC)</label><input type="datetime-local" class="form-control privacy-release-at"></div><div class="privacy-event mt-2 d-none"><label class="form-label">Release event</label><select class="form-select privacy-event-id"></select></div>`;
    const type = wrap.querySelector('.privacy-type');
    const users = wrap.querySelector('.privacy-users');
    const event = wrap.querySelector('.privacy-event-id');
    type.addEventListener('change', () => { wrap.querySelector('.privacy-specific').classList.toggle('d-none', type.value !== 'specific_people'); wrap.querySelector('.privacy-date').classList.toggle('d-none', type.value !== 'release_date'); wrap.querySelector('.privacy-event').classList.toggle('d-none', type.value !== 'release_event'); });
    wrap.loadRule = async (resourceType, resourceId) => { const r=await fetch(`${PRIVACY_API}/list.php?resource_type=${encodeURIComponent(resourceType)}&resource_id=${resourceId}`); const d=await r.json(); const rule=d.data?.rule; if(!rule)return; type.value=rule.visibility_type; wrap.querySelector('.privacy-release-at').value=rule.release_at ? rule.release_at.replace(' ','T').slice(0,16) : ''; if(rule.user_ids?.length){ await loadPrivacyUsers(users,ownerId); [...users.options].forEach(o=>o.selected=rule.user_ids.includes(Number(o.value))); } if(rule.release_event_id){await loadPrivacyEvents(event);event.value=rule.release_event_id;} type.dispatchEvent(new Event('change')); };
    wrap.getRule = () => ({ visibility_type:type.value, user_ids:[...users.selectedOptions].map(o=>Number(o.value)), release_at:wrap.querySelector('.privacy-release-at').value, release_event_id:Number(event.value||0) });
    loadPrivacyUsers(users, ownerId); loadPrivacyEvents(event); return wrap;
}
async function loadPrivacyUsers(select, ownerId) { try { const d=await fetch(`${PRIVACY_API}/users.php?owner_id=${ownerId}`).then(r=>r.json()); (d.data?.users||[]).forEach(u=>{const o=document.createElement('option');o.value=u.id;o.textContent=u.full_name;select.appendChild(o);}); } catch(e){} }
async function loadPrivacyEvents(select) { try { const d=await fetch(`${PRIVACY_API}/events.php`).then(r=>r.json()); (d.data?.events||[]).forEach(e=>{const o=document.createElement('option');o.value=e.id;o.textContent=`${e.title} (${e.status})`;select.appendChild(o);}); } catch(e){} }
async function savePrivacyRule(token, resourceType, resourceId, rule, inherit=false) { const r=await fetch(`${PRIVACY_API}/save.php`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify({resource_type:resourceType,resource_id:resourceId,...rule,inherit_from_folder:inherit})}); const d=await r.json(); if(!d.success) throw new Error(d.message||'Privacy rule failed'); return d; }
