<?php
require_once __DIR__ . '/_helpers.php';
if($_SERVER['REQUEST_METHOD']!=='POST'){ApiResponse::send(false,[],'Method not allowed',[],405);exit;}
$owner=privacy_auth();$d=privacy_data();privacy_csrf($d);$type=trim((string)($d['resource_type']??''));$id=(int)($d['resource_id']??0);$visibility=(string)($d['visibility_type']??'');
if($type===''||$id<=0||!in_array($visibility,PrivacyService::allowedTypes(),true)){ApiResponse::validation(['privacy'=>'Invalid privacy rule']);exit;}
try{$db=privacy_db();$existing=PrivacyService::getRule($db,$type,$id);if($existing&&(int)$existing['created_by']!==$owner&&!SessionHelper::isAdmin()){ApiResponse::forbidden();exit;}
 $users=PrivacyService::validateUsers($db,(array)($d['user_ids']??[]),$owner);$releaseAt=$visibility==='release_date'?trim((string)($d['release_at']??'')):null;$eventId=$visibility==='release_event'?(int)($d['release_event_id']??0):null;
 if($visibility==='release_date'&&(!$releaseAt||strtotime($releaseAt.' UTC')===false)){ApiResponse::validation(['release_at'=>'Valid UTC release time required']);exit;}
 if($visibility==='release_event'&&$eventId<=0){ApiResponse::validation(['release_event_id'=>'Release event required']);exit;}
 $db->beginTransaction();$q=$db->prepare("INSERT INTO privacy_rules(resource_type,resource_id,visibility_type,release_at,release_event_id,inherit_from_folder,created_by) VALUES(:t,:i,:v,:r,:e,:h,:c) ON DUPLICATE KEY UPDATE visibility_type=VALUES(visibility_type),release_at=VALUES(release_at),release_event_id=VALUES(release_event_id),inherit_from_folder=VALUES(inherit_from_folder),updated_at=CURRENT_TIMESTAMP");$q->execute(['t'=>$type,'i'=>$id,'v'=>$visibility,'r'=>$releaseAt?:null,'e'=>$eventId?:null,'h'=>(int)(bool)($d['inherit_from_folder']??false),'c'=>$owner]);$rid=$existing?(int)$existing['id']:(int)$db->lastInsertId();$db->prepare('DELETE FROM privacy_rule_users WHERE privacy_rule_id=:id')->execute(['id'=>$rid]);$u=$db->prepare('INSERT INTO privacy_rule_users(privacy_rule_id,user_id) VALUES(:r,:u)');foreach($users as $uid)$u->execute(['r'=>$rid,'u'=>$uid]);$db->commit();ApiResponse::success(['rule_id'=>$rid],'Privacy rule saved');
}catch(InvalidArgumentException $e){if(isset($db)&&$db->inTransaction())$db->rollBack();ApiResponse::validation(['user_ids'=>$e->getMessage()]);}catch(Throwable $e){if(isset($db)&&$db->inTransaction())$db->rollBack();error_log('Privacy rule save: '.$e->getMessage());ApiResponse::serverError('Unable to save privacy rule');}
